#!/usr/bin/env python3
"""Build the deterministic Markdown knowledge package for the custom GPT.

The builder intentionally reads every direct ``references/*.md`` file rather
than maintaining a second, manually curated source list.  The source list in
the generated document is therefore always aligned with the files present in
the repository, including references added by another process.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import List, Optional, Sequence, Tuple


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_OUTPUT_NAME = Path("assets") / "china-esg-carbon-accounting-knowledge.md"


class BuildError(RuntimeError):
    """Raised when the knowledge package cannot be built."""


def _resolve_path(value: Optional[Path], default: Path) -> Path:
    """Resolve a CLI path without depending on the caller's working directory."""

    if value is None:
        return default.resolve()
    return value.expanduser().resolve()


def _source_files(references_dir: Path) -> List[Path]:
    """Return all direct Markdown references in deterministic order."""

    if not references_dir.is_dir():
        raise BuildError(f"references directory does not exist: {references_dir}")

    files = [
        path
        for path in references_dir.iterdir()
        if path.is_file() and path.suffix.lower() == ".md"
    ]
    files.sort(key=lambda path: (path.name.casefold(), path.name))
    if not files:
        raise BuildError(f"no Markdown references found in: {references_dir}")
    return files


def _read_normalized(path: Path) -> str:
    """Read UTF-8 text and normalize line endings for portable output."""

    try:
        # utf-8-sig accepts regular UTF-8 and harmlessly removes a BOM if one
        # was introduced by a Windows editor.
        text = path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError as exc:
        raise BuildError(f"reference is not valid UTF-8: {path} ({exc})") from exc
    except OSError as exc:
        raise BuildError(f"cannot read reference: {path} ({exc})") from exc

    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Every section gets exactly one trailing newline.  Leading whitespace and
    # internal formatting remain source-controlled content.
    return text.rstrip() + "\n"


def _build_date(value: Optional[str]) -> str:
    """Return an ISO date, honoring reproducible-build conventions."""

    if value:
        try:
            return date.fromisoformat(value).isoformat()
        except ValueError as exc:
            raise BuildError(
                f"--build-date must be an ISO date (YYYY-MM-DD): {value}"
            ) from exc

    # SOURCE_DATE_EPOCH makes repeated builds byte-for-byte reproducible when
    # a release pipeline supplies it.  It is intentionally optional so a
    # normal local build still records the local calendar date.
    source_date_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if source_date_epoch:
        try:
            timestamp = int(source_date_epoch)
            return datetime.fromtimestamp(timestamp, tz=timezone.utc).date().isoformat()
        except (ValueError, OverflowError, OSError) as exc:
            raise BuildError(
                "SOURCE_DATE_EPOCH must be a valid Unix timestamp"
            ) from exc

    return datetime.now().astimezone().date().isoformat()


def _render_package(
    repo_root: Path,
    source_files: Sequence[Path],
    build_date: str,
) -> str:
    """Render a UTF-8 Markdown package with provenance and source sections."""

    entries: List[Tuple[str, str, str]] = []
    version_path = repo_root / "VERSION"
    release_version = (
        _read_normalized(version_path).strip() if version_path.is_file() else "unversioned"
    )

    for path in source_files:
        content = _read_normalized(path)
        relative_name = path.relative_to(repo_root).as_posix()
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        entries.append((relative_name, digest, content))

    lines = [
        "<!-- Generated by scripts/build_gpt_knowledge.py. Do not edit this file directly. -->",
        "# China ESG & Carbon Accounting Knowledge",
        "",
        f"- Release version: `{release_version}`",
        f"- Build date: `{build_date}`",
        "- Source directory: `references/`",
        f"- Source file count: `{len(entries)}`",
        "",
        "## Source files",
        "",
    ]
    for index, (relative_name, digest, _content) in enumerate(entries, start=1):
        lines.append(f"{index}. `{relative_name}` (SHA-256: `{digest}`)")

    lines.extend(["", "---", ""])

    for relative_name, digest, content in entries:
        lines.extend(
            [
                f"## Source: `{relative_name}`",
                "",
                f"<!-- Source SHA-256: {digest} -->",
                "",
                content.rstrip("\n"),
                "",
                "---",
                "",
            ]
        )

    # Avoid an extra separator after the final section while retaining one
    # final newline, as required for stable Markdown and POSIX tooling.
    while len(lines) > 1 and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def build_package(
    repo_root: Path,
    output_path: Path,
    build_date: Optional[str] = None,
) -> Tuple[Path, List[Path], str]:
    """Build and write the package; return output, sources, and date."""

    repo_root = repo_root.resolve()
    output_path = output_path.resolve()
    sources = _source_files(repo_root / "references")
    resolved_date = _build_date(build_date)
    rendered = _render_package(repo_root, sources, resolved_date)

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        # ``Path.write_text(..., newline=...)`` is unavailable on some older
        # Python versions still found on Windows.  Opening explicitly keeps
        # the script portable while forcing LF output on every platform.
        with output_path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered)
    except OSError as exc:
        raise BuildError(f"cannot write knowledge package: {output_path} ({exc})") from exc

    return output_path, sources, resolved_date


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge references/*.md into a deterministic GPT Knowledge Markdown package."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=DEFAULT_REPO_ROOT,
        help="repository root (default: the parent of this scripts directory)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="output Markdown path (default: <repo>/assets/china-esg-carbon-accounting-knowledge.md)",
    )
    parser.add_argument(
        "--build-date",
        help="build date in YYYY-MM-DD format; otherwise SOURCE_DATE_EPOCH or local date is used",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    repo_root = _resolve_path(args.repo_root, DEFAULT_REPO_ROOT)
    output_path = _resolve_path(
        args.output,
        repo_root / DEFAULT_OUTPUT_NAME,
    )

    try:
        written_path, source_files, resolved_date = build_package(
            repo_root=repo_root,
            output_path=output_path,
            build_date=args.build_date,
        )
    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Built knowledge package: {written_path}")
    print(f"Build date: {resolved_date}")
    print(f"Source files ({len(source_files)}), deterministic order:")
    for path in source_files:
        print(f"  - {path.relative_to(repo_root).as_posix()}")
    print(f"UTF-8 bytes written: {written_path.stat().st_size}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
